export {default as Login} from "./Login/Login";
export {default as Register} from "./Register/Register";
export {default as Home} from "./Home/Home";
export {default as OtpVerification} from "./OtpVerification/OtpVerification";
export {default as VerifiedOTP} from "./VerifiedOTP/VerifiedOTP";
export {default as SplashScreen} from "./SplashScreen/SplashScreen";
export {default as CartItems} from "./CartItems/CartItems";
export {default as MyAccount} from "./MyAccount/MyAccount";
export {default as ProductDetails} from "./ProductDetails/ProductDetails";
