export default {
    LOGIN:"LOGIN",
    ADD_CART:"ADD_CART",
    ISLOGIN:"isLoggedin",
    ADD_ITEM_COUNT:"ADD_ITEM_COUNT",
    SUBTRACT_ITEM_COUNT:"SUBTRACT_ITEM_COUNT",
    TOTAL_PRICE:"TOTAL_PRICE",
    DELETE_ITEM:"DELETE_ITEM",
    ON_LOGOUT:"ON_LOGOUT"
}